package br.com.finsavior.model.enums;

import lombok.Getter;

import java.util.List;

@Getter
public enum Prompt {
    PROMPT_MONTHLY(List.of("Considere o consumo do mês através das informações das minhas finanças do período de 1 mês abaixo:\nLevando em consideração os dados das tabelas abaixo: \n", "E os dados da tabela de cartão de crédito que detalha o valor do registro 'Cartão de crédito' da tabela anterior: \n", "E as legendas de cada tipo de conta:\n* Ativo: Direito ou valor que ficará disponível para ser encorporado à liquidez no futuro, exemplo: vale-alimentação, pagamento de empréstimo a receber, restituição de imposto, etc...\n* Passivo: Obrigação ou valor a diminuir da liquidez, exemplo: aluguel, parcela de carro, iptu, etc...\n* Caixa: Representa a injeção de valor valor imediato e disponível na liquidez, por exemplo: saldo de conta em banco.\n *Liquidez: Representa o seu estado financeiro atual: Liquidez=(Ativo+Caixa)-Passivo.\n\n", "Quais são suas considerações sobre minhas finanças? Está tudo bem? Tenho muitos gastos com algo que não deveria? Tem qualquer observação que me ajude sobre as minhas finanças? Estou fazendo algo certo? Se não estou bem financeiramente, o que você sugere de mudanças ou cortes? Como posso me organizar para poupar o máximo de dinheiro possível mensalmente? Qualquer dica ou insight que você tenha para me ajudar com esse assunto é bem vinda. Faça a análise mais profunda possível dos dados que te enviei a fim de me dar o melhor direcionamento financeiro."), AnalysisType.MONTH),
    PROMPT_TRIMESTER(List.of("Considere o consumo do trimestre a seguir através das informações das minhas finanças do período de 3 meses abaixo:\nLevando em consideração os dados das tabelas cada uma representando um mês abaixo: \n", "E os dados de cada uma das tabelas de cartão de crédito que detalham o valor do registro 'Cartão de crédito' das tabelas anteriores respectivamente: \n", "E as legendas de cada tipo de conta:\n* Ativo: Direito ou valor que ficará disponível para ser encorporado à liquidez no futuro, exemplo: vale-alimentação, pagamento de empréstimo a receber, restituição de imposto, etc...\n* Passivo: Obrigação ou valor a diminuir da liquidez, exemplo: aluguel, parcela de carro, iptu, etc...\n* Caixa: Representa a injeção de valor valor imediato e disponível na liquidez, por exemplo: saldo de conta em banco.\n *Liquidez: Representa o seu estado financeiro atual: Liquidez=(Ativo+Caixa)-Passivo.\n\n", "Quais são suas considerações sobre minhas finanças? Está tudo bem? Tenho muitos gastos com algo que não deveria? Tem qualquer observação que me ajude sobre as minhas finanças? Estou fazendo algo certo? Se não estou bem financeiramente, o que você sugere de mudanças ou cortes? Como posso me organizar para poupar o máximo de dinheiro possível mensalmente? Qualquer dica ou insight que você tenha para me ajudar com esse assunto é bem vinda.  Faça a análise mais profunda possível dos dados que te enviei a fim de me dar o melhor direcionamento financeiro."), AnalysisType.TRIMESTER),
    PROMPT_ANNUAL(List.of("Considere o consumo do ano através das informações das minhas finanças do período de 12 meses abaixo:\nLevando em consideração os dados das tabelas cada uma representando um mês abaixo: \n", "E os dados de cada uma das tabelas de cartão de crédito que detalham o valor do registro 'Cartão de crédito' das tabelas anteriores respectivamente: \n", "E as legendas de cada tipo de conta:\n* Ativo: Direito ou valor que ficará disponível para ser encorporado à liquidez no futuro, exemplo: vale-alimentação, pagamento de empréstimo a receber, restituição de imposto, etc...\n* Passivo: Obrigação ou valor a diminuir da liquidez, exemplo: aluguel, parcela de carro, iptu, etc...\n* Caixa: Representa a injeção de valor valor imediato e disponível na liquidez, por exemplo: saldo de conta em banco.\n *Liquidez: Representa o seu estado financeiro atual: Liquidez=(Ativo+Caixa)-Passivo.\n\n", "Quais são suas considerações sobre minhas finanças? Está tudo bem? Tenho muitos gastos com algo que não deveria? Tem qualquer observação que me ajude sobre as minhas finanças? Estou fazendo algo certo? Se não estou bem financeiramente, o que você sugere de mudanças ou cortes? Como posso me organizar para poupar o máximo de dinheiro possível mensalmente? Qualquer dica ou insight que você tenha para me ajudar com esse assunto é bem vinda.  Faça a análise mais profunda possível dos dados que te enviei a fim de me dar o melhor direcionamento financeiro."), AnalysisType.ANNUAL);

    private final List<String> promptParts;
    private final AnalysisType analysisType;

    Prompt(List<String> promptParts, AnalysisType analysisType) {
        this.promptParts = promptParts;
        this.analysisType = analysisType;
    }
}
